# -*- coding: utf-8 -*-
"""minst_data_model_Jatin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cnf0KXsvq99ep-OswCg9dsxR1YGwgqQy
"""

#mount drive.

from google.colab import drive
drive.mount('/content/drive')

#unzip and extract the dataset file.

import zipfile
import os
zip_path = "/content/drive/My Drive/mnist/Minst Dataset.zip"
extract_path = "/content/mnist_data"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

#Load the dataset as images into train and test variables for image and labels.

import numpy as np
import os

# Paths to dataset files
train_label_path = os.path.join(extract_path, "Mnist_Train_Label.npy")
test_label_path = os.path.join(extract_path, "Mnist_Test_Label.npy")
train_npy_path = os.path.join(extract_path, "train_npy")
test_npy_path = os.path.join(extract_path, "test_npy")

# Load labels
train_labels = np.load(train_label_path)
test_labels = np.load(test_label_path)

# Load images
train_images = np.array([np.load(os.path.join(train_npy_path, f)) for f in sorted(os.listdir(train_npy_path))])
test_images = np.array([np.load(os.path.join(test_npy_path, f)) for f in sorted(os.listdir(test_npy_path))])

# Normalize pixel values (0-255 → 0-1)
train_images = train_images / 255.0
test_images = test_images / 255.0

# Check shapes
train_images.shape, test_images.shape, train_labels.shape, test_labels.shape

import tensorflow as tf
from tensorflow import keras

# Build a CNN model
model = keras.Sequential([
    keras.layers.Conv2D(128, (3,3), activation='relu', input_shape=(28,28,1)),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3), activation='relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(128, (3,3), activation='relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(64, (3,3), activation='relu'),
    keras.layers.MaxPooling2D(2,2),

    keras.layers.Flatten(),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dropout(0.3),  # Helps prevent overfitting
    keras.layers.Dense(10, activation='softmax')
])

# Compile the model
model.compile(optimizer=keras.optimizers.SGD(learning_rate=0.01, momentum=0.9),
              loss='categorical_crossentropy',
              metrics=['accuracy'])


# Print summary
model.summary()

#train the model.

model.fit(train_images, train_labels, epochs=10, validation_data=(test_images, test_labels))

#evaluation

test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"Test Accuracy: {test_acc * 100:.2f}%")

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files


uploaded = files.upload()

def preprocess_image(image_path):
    # Load the image in grayscale mode
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)

    # Resize the image to 28x28 pixels
    image_resized = cv2.resize(image, (28, 28))

    # Invert colors (MNIST uses white-on-black)
    image_inverted = 255 - image_resized

    # Normalize (0-255 → 0-1)
    image_normalized = image_inverted / 255.0

    # Reshape to match model input (28x28 → 28x28x1)
    image_reshaped = image_normalized.reshape(1, 28, 28, 1)

    return image_reshaped

# Example usage
custom_image_path = "/path/to/your/image.png"  # Change this
processed_image = preprocess_image(custom_image_path)

# Display the processed image
plt.imshow(processed_image.squeeze(), cmap="gray")
plt.title("Processed Image")
plt.axis("off")
plt.show()